travis:
  secure:
    BINSTAR_TOKEN: mwOxoKgLh46Fh7y0E8DytPFQtV8I8A+NBgFirLNwSEfdfTfbczNFDCTcXty6FTYylE+sllQkpmchELktX3x+JFSI1AsXfvbFMulJmliFkGqwGHYZLe/GEvIbSBiKM+HZ11p4dcCNqRIl9A5CCASlcip0unVEqTIQkeK6tTV950VSFwvdFXgIB/kw6iCfoRUxZaADC9MeckpcyJfEIIP5ZBuQ7vjqnlp9+DlfaINK85jjeMHobtmzcsSxqjlskuOoGZt6tUdM7BMlb3RT6rBaC+Fik+ungfePrCEpbMXHTEgqC9kmkMl82ihVfnzpHdMI5afXcf9u8OxO7J9oMT4K/EW2dzKzsk1zqegkQjdVxkWgeU+c1NYV2cbGK/AT2bhNVkLfHhrAvIyNtSMj4+yfkM4ZFbHf7I1sgzxXl3V5evGIt403GO6iPsHw0QZCifxKqF90iu2Bxju7HOXTgGKDFvZ6ftvajFT1QMDUe8e6t54Cq/AY83DItdMOdugXcBP4w0OO+Y0/+ijzvgQ/aSrjiNGqCGsJt1Q1VYc1lvsjnSgfR2gxCfRMy6IlVLNPLpSTbS3/Kv7MGK5W/UIMZa791VjV10Jlp2FFgFbMQmAVS/JmjNPUxjq/GQ+M1o53cfh+2SJ1L5R/A0hoTAQOuCwRHsRjde8rTO4TtZeIHLXvxxk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
