travis:
  secure:
    BINSTAR_TOKEN: Y5YBVdiFAIozfGchApMbgjecKTzG3skY4GHebhgI6XGlmvyvtI/xcmfbsJQOGUziSpruws57hUuvfAeqWhnbBj3BNfcmQEteKbHr5fJViGtd84qUCg7quw7ZtLt9ULR/AYzsFSxb69+GJIwZyE4sMgGhCZM0pqyUXgX0zOFe+Ol8egzfjG8spE/UgsFCF/E3qPldzx6K075czaEAczrQLM2Z+p9Y24mQ1ijU51Bc9uOct360b9RG804LFziNLHTNPxKn7EXQ5l/u7MxrUPxRx5U8XG+oUIyHMYrH2sLbNEoJR29TmPeVn2sPLGE9Pl7mzPwWpdLOP7pK4zZ+4PCepY7zob24vvK1oL/X/olGJ8LBJFs6XVMV3oSY78fVskrSoiSQBs0W9FXMLmd6yOUMDCdr/rmx8+6F/o2sEVyHcdX4jQqr7FAQ+Fc99ZXxpnvLK3iGeWtzZCsxw60YBmaWWPeYAdILUE3Bt+5fEaKHhnLJghs26ZcIjc28aONUY01a5joWdaVNnJoMYsFaC9yyuUs0YTr4s1o+uo19EzCEUS1ZV39vff8Yw3t2wI38dHJXggWOJk88//iktrORf/ccaUtPAFTAOIDgfysMbmen/HhsQ1qAPSPTUC0e5T2ZbYrSCdGANMSmBcfXk4zt7drD+Pcc7At9WFehmXevpQUm/uU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
