travis:
  secure:
    BINSTAR_TOKEN: fFQZHlavhUwT5MEm55oenLP0CapLTZiPOqNZUC4hRxf2b6F6DNa1StKS1JHDBfERX7Zyfhy8vGQ17L7yrgimYVmvtrdMYIq9qXi5lMwes48+DiEheS9BCnv5kpggpBADLaIPRdfxD9GTYhBBA+zkMavTgZGPKI+iSJg/YwsPz/PHeAAToRjKzFMm04y/FGpHfPiU1hmUW+DHBXTiA5ltLIAzCg2vwg+DRc97TuK4eQrTrqBHimOWgmTs4pEcgiBx3boNXV+8po1nhBXkI1WicTOc1ceLuu29aVWki7d5/FckTeU37fk0SW1uxtHYDy3OqCwaZJePI2lfWS91pc8vYedFflx5xJx40FKFAmeAyHTL1mAIaytgILXhDXf8UOPTnMJaFNPcs1M2/QWmQtKHdBRN3PBvM2Iyyp12NBRlsC7rGRco9ZdiHlSW60DyimIEPa3ClnNDonkjwiHQasYp9Q066uL24uXewo8Ou9R1ugTqlRPNM5meaOqLI6Xav14aWT8P5t/GiIwWafLEFQg7n5+BpNTTWAV5Kgc1saiWPmMlfHTG7+RSJ6fAD0e0WLV7lz+b+6bXafK2QKr+pUILGgYNsEWGQOvW+Pio3XHZuCY7/IW1vKD0vBQKX9ossqoDt7Z565mVvK6LwIrid5xtgaeTUXT3KbkzjXrDnAVEoJY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
