travis:
  secure:
    BINSTAR_TOKEN: pdg0wJn+k0EsqVLdAQoCGJKVblgSu5VwT/6bLU5zDUnweiDMvGHK9yz4TUpgP1Wzb5l0PW6xIQGx1Z3c9ifcUQL6WbQ6tcLPCJMU27SFMfdHi9hfszb2BZKX10qnDjbyBWrrdKz/vHnjLTEvS9tmXuP1EYLBaFmmMtau4WvDEV56CL11RsoMOs169H9ifpamd3EMX7mCJ90gOawrYTeDQRPAXkmlBFDYIcDVnIrWtqAO6Ky8STRqFO2ljEE551QI88nc5NKyF8abZMFWMEB2HRsNbg5TD8kgqMT2vMxg3nGfY49caEGMRfSQRU5j9oSKRQZkGdfVyCCTRuaQZmaSCnabQppwgx4GvPkdmWYouEq81zzfD6gsZdN0IZq8Pm8S9gNv1YNaMNAZJhTGQQPNm+022hnFpq5FutGIg5AjfXeURy5n6woXt7gQSAZYr7Ghsu42NaLRPuclom1raoADTd7yp2lJPfbvMU4iypHz/YEpZiUuuLwbqoSs9pNSmHrbzs2deguYeT8/Mt5eW/OjDd6BxpJYUo2s+7d7rrXUXsH+oa/whzcFQIr2aHViwA+3bAEgVJPdOw8nu34pBjVyk6AgYFlngtzXKTvGKRcneaUcceQXOVK/MD9tTZg6PYRx55aycH2v/kYIgEBQ4BlH4h2l9zJfM+hsWHzwXLef6QU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
