travis:
  secure:
    BINSTAR_TOKEN: Hh9cd4do+4A9wIwrdxMOwjpXTOMHjshbA5muiliD9wttFta6zbu5pW427Bz6Vy/6Ik7GI/14Pi1f+d7Jw1fJbVKMRCAxS79jvRem2Ccev+0Qlzz09sNS2VtzcIeF7svh4ol+wpo5Gz2OV/us2NDNcg8r79Bh0O1b8Du77+Uw3ZwrHIF4dl9Z4ycEIvVLXIWtCxG3fHRl7qLVJTDwgfIpP7HpCS1pP2RnbVAWBU6lERmU8sQUTZQeqv2Rd1lo5Da2M56U1pgOBFINo9dU0S0oP67FqznaneeBL5w5LlB67q1m668MJXjYhUsndOoXZHDzkkjAs5z8txBeGIqEaqCvFF9e8pflyYKDtYsp65tnESo1nVgV8Yan96s/exWezXW1vVb6WTdqz8Mnu7xq2TqWIOKgi6SRmcUFVFQJyTJHhW6Gib63q8vPqTz3pRhU86lUQmH0zzGkJNt8lXJrbYkpsCV9n+j3qMIb7KYpqDGXQ61GPg1OrxQ9qvUCal/DoZqb2n/z+EzAD45sADyi6iUcgnhe44gv/z8wQABGJp7NjRsls42wRTC6nchjnwigyT1eLaMwvGXsrKKyHIn104BMkr8xjDLg77F2ACdA5hmb0xVjZMRpx2ZIZkfriS1dOwVoHtz8NQAsb6lrm2fuyvy2ap669sz1dvTvQpzxuWebcng=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
