travis:
  secure:
    BINSTAR_TOKEN: ntZnvlKT3/e4TG8p6R7lInDyGl/n2BL6fScLuNyJYJzwdGwCDHvkCq7uxjL3KAL6aH5xMHFud1+OsbArvS7OYWSt3/gZLloKsDf4shDofIFr4Hy9gOewXc32/nW6vBJwZAmmxlVywViO63gGdIciBTqt1KzQPL38+vq5whLMzqGlYExxFQcuOvEXCyuit+OdjIrEMsmWIngEGJQJ2zNe78JJ2Tkiq5bdIev7oQVlgB8e2XDCz9KDBujsS8q2RzAtuZpyJHO3p1wNu/ECHuTXRV+bK5/pBt4nMcR9kyO/mubUeUpbwMoz9BNlrl+izRg/sfNOH6a2jhKu7i3sMISxFeqGpoYXpKqmUwXR4rpPUIOZpcJB+H/ASuuirqVxnkWAhNYDFxfQuykwriCKnuibRiVV+X86aZfbWBh591Qvj3qCW8pDpE6ZmiCMrYl/l64Ax3rxNzpe+O/vwpWHkpYpifUZSdGOskyyahIBMPlSR4JxI8BkDPgnTJkQLQsan8It2ONb/F59vbWjSrYWTwmgOAvcYveCxmHUCYvnfQ1bB9N4YIEMNMKDqwRfSodrzLAMKnZONmwCRgK+foBtlKh8bQzPmDp7lAIfiEvVzAWeNoxdUN0yWh0uew0mHIUyNOkohny7aJY85FLIGCRZ0QNOC1YPY81jYmckwrQKJKeciRw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
