travis:
  secure:
    BINSTAR_TOKEN: L1a0IlY3S6l0FfF1p6RON9J5cjXoy7avbSH2AdaLuJkRyNYt6XJ8sLl7BS5DT3eNqgisqHhXrxRGRTqpXC07QI5nWxb/nX5RQ7sGPfGpdYyWGr/wnrF39SzjsA4GRF5VXwXKb/3oxDLBfzkkKstHDeSlIFXj+PRe79j/NsbC7Bo/kvcZ1IVPJrFiDb1xYtYcCiTJ7ljGvtLK8cLB6ZnDeRyBqGLwKfzhLMmmVLNylVqBq5LhtirHfJe1pBMZWk3g5YgHR4Lcen5gTEqrOgm4I81mi8KCkd+/GzPkYwWkbGiTej7JxdbMTQaYKXtmYePqZDkW2l21TVAFgBAw2+t2Gs/FSDkghBc4l7QQ8TKlq8gy/c6TEicisVyRvMtrGN/6ckh6Bf/BhqXQfAL0sjBDaLTpzTo6AFXGzOQEXVNooZqmitbLgDa62BUYmPS+Zr0uOnhyf071UoHPbwf2JSF6uqvs3vn/M1RFih3Mx5I2PlXKiV/nER+feRU7LWRzC2cQIirzltQZ8H2y0BmjwfBnhgnqEASSCUsD6BLZ/7HLOcTqgmmctN0JAfvS3BrfJCEnisRzqnaTL9E5afRrp+6X+RoyjG4kfu9Dt0BR6Ri2nIoG/wXxs5Fa95EEJ0O7aIWpvx1BgnqA1walAqnf2ZqB6CZ5WNOV3wX3qJJopUySK5E=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
